#!/bin/sh
set -e
# Automatically added by dh_dkms
DKMS_NAME=rtl8723ds-mp-driver
DKMS_VERSION=5.1.1.2-18132.20160706-BTCOEX20160510-0909-ntc

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
